# Generated by Django 5.1.1 on 2024-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_course_alter_professor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('id_estudiante', models.IntegerField()),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('nombre_materia', models.CharField(max_length=100)),
                ('descripcion_materia', models.TextField()),
                ('nombre_profesor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
